### ISSUE TITLE
Improve the home window

### ISSUE THREAD

**Issue by roonyh** [roonyh/fossasia-gci-companion#1]
Use material design to improve the UI http://materializecss.com/

**Comment by YagoGG** [comment]
Hi! I'd like to work in this issue.
I was also wondering if it's a problem to use [MDL](http://www.getmdl.io) instead of Materialize, since I feel more comfortable with it, and I think it's more robust.

**Comment by roonyh** [comment]
@YagoGG Sure. Use MDL. @shashank-sharma is also working on the UI. But with experience gained from working on this would be useful for follow up work. So don't feel bad if only one of your work will be merged :) Because there will be more issues regarding the UI following up to work on.

Looking forward for a PR.

**Comment by YagoGG** [comment]
Great! Thanks.

**Comment by shashank-sharma** [comment]
@roonyh It's great if @YagoGG is working. Currently I have been facing problem with npm start as it showing error and I am trying to find out the error so that's why I am updating most of my files. Still it might take loads of time to update and then after-all I really don't have much experience so its better if YagoGG will do. I will learn few things and if possible I might help later.

**Comment by YagoGG** [comment]
@shashank-sharma, I also had some trouble with the setup. If you want to chat and see if I can help, I'm on Freenode IRC #fossasia channel ;)

**Comment by roonyh** [comment]
@shashank-sharma @YagoGG Please show me the error. If you had trouble tell me. Don't be stuck in this initial step. If you report the troubles you had chances are we can fix something so that someone else's time is saved from going over the same thing. I also am available on #fossasia.  

Again, Please ask for help If you are stuck for more than half an hour or so. Its fine.

**Comment by YagoGG** [comment]
@roonyh I solved mine in 10 minutes, wasn't a big deal (my node and npm packages were too old), but thanks for your disposition!

**Comment by roonyh** [comment]
@YagoGG ah. Great! glad its resolved :)

**Comment by shashank-sharma** [comment]
@roonyh I also saw that link which @YagoGG provided me I just wanted to update some files. And I guess after that update it will work fine

**Comment by roonyh** [comment]
@shashank-sharma ok. great!

**Comment by roonyh** [comment]
#7 is a great starting point. We can close this and add further issues for new UI feature requests.
