### ISSUE TITLE
Add people to gci15 website

### ISSUE THREAD

**Issue by roonyh** [roonyh/fossasia-gci-companion#13]
To add a mentor or student profile to the [gci15 website of FOSSASIA](http://gci15.fossasia.org/) one has to make a commit. We can make this commit from the companion app.
- Give users a form to add name, credentials and bio.
- Add some method to give the photo. Drag and drop would be best.
- make the commit.

For the moment you can hardcode the repository path. onese #2 is fixed we can allow the users to give it.

Once #3 is fixed we can actually make the PR from the app.

**Comment by anshuman73** [comment]
I'd like to work on this one !

**Comment by anshuman73** [comment]
But should I wait till #2 and #3 are done? Cause you'll be changing the file structure too I guess. I could help you with that too, if you'd like.

**Comment by roonyh** [comment]
You don't have to wait for #2 #3 and I am much more eager to get this done than changing the file structure :)

**Comment by roonyh** [comment]
@anshuman73 Let me know if you still want to work on this. Its totally fine if you don't want to do this at the moment. Please comment here, so someone else can pick this up.

**Comment by anshuman73** [comment]
well, I'm still facing troubles in even installing electron on my windows. I think I'll release this work, so that I don't stop the important workflow. I'll start contributing again as soon as I can. Sorry. I hope you understand :(

**Comment by roonyh** [comment]
@anshuman73 of course. no problem what so ever. thanks for letting us know.
