### ISSUE TITLE
add a little more detail to README.md

### ISSUE THREAD

**Issue by abdulhannanali** [roonyh/fossasia-gci-companion#4]
hi, 
how will it help the students and mentors with their tasks?  Please tell something about it too. Thank you

**Comment by abdulhannanali** [comment]
especially can you tell more about what tasks it will perform in order to help the students and mentors :smile:

**Comment by roonyh** [comment]
Sure. Some info is there under _features_. At the moment the main plan is to help students with git. For example with [students website](http://gci15.fossasia.org/). It's on GitHub pages. So to add ones information they have to make a git commit. Though it's fun using git with a terminal emulator maybe it's easier with a graphical interface. 😀 

Moving on we can allow students and mentors manage there GitHub repositories. Desktop notifications for GitHub events, managing licenses and readmes. 

We can also use the api of codein.withgoogle.com for mentors. I will add those info with time.

**Comment by abdulhannanali** [comment]
@roonyh how will we solve the binaries problems for electron and nodegit? If I am right, nodegit has separate binaries for each platform, can electron take care of that as well?

**Comment by abdulhannanali** [comment]
@roonyh how about focusing on UI and front end with electron and using nodegit at a backend? It will save us hassle of replying why's and why nots?

**Comment by abdulhannanali** [comment]
i am just asking would it be a viable option to keep nodegit at the backend? :smile:

**Comment by roonyh** [comment]
We don't need to worry about the correct binary. see http://www.nodegit.org/guides/install/electron/  
`npm install` will fetch the correct binary based on the entry for engine. yay! 
But I noticed that having the same node version as the electron version (5.1.0 for latest electron) is important. Maybe `npm install` builds nodegit locally. All in all its not a problem.

**Comment by roonyh** [comment]
I assume backend = [main process](http://electron.atom.io/docs/v0.36.0/tutorial/quick-start/#main-process) and frontend = [renderer process](http://electron.atom.io/docs/v0.36.0/tutorial/quick-start/#renderer-process).  

So you suggest that we start a node server and make ajax requests to it from renderer processes? Hmm yes that would be ideal. But development would be easier the current way. And we will use seperate modules to keep nodegit seperated from frontend so if the need arises we will do it that way.  

At the moment I am excited about making a usable app than worrying too much about the architecture. I don't think the electron community themselves clear conventions about those things :)

**Comment by abdulhannanali** [comment]
@roonyh seems cool! thanks for clearing out
