### ISSUE TITLE
Write a wiki article about using electron

### ISSUE THREAD

**Issue by roonyh** [roonyh/fossasia-gci-companion#8]
- Describe how electron brings web technologies to desktop apps
- Give some tips to web developers who are starting to work on electron
  - like not having to worry about making the app cross browser
- Examples for things that only a desktop application can do. (Can't do in a website)
  - like accessing the local files of the user without a hassle

Article should go here: https://github.com/roonyh/fossasia-gci-companion/wiki

**Comment by shashank-sharma** [comment]
I would like to work on this Issue, it might help me to understand electron more clearly and it will help others too.

**Comment by roonyh** [comment]
@shashank-sharma great :+1:  thanks for picking this up.

**Comment by shashank-sharma** [comment]
@roonyh  I have made an edit. Please take a look at [wiki](https://github.com/roonyh/fossasia-gci-companion/wiki) page.

**Comment by roonyh** [comment]
@shashank-sharma looks good on a quick look. I will go through it again in a few minutes. In the mean time provide links to any resources giving credit that you referred.

**Comment by shashank-sharma** [comment]
@roonyh  I have added the links. I hope its fine now.

**Comment by abdulhannanali** [comment]
@roonyh there are some changes to be made i'll review it :)

**Comment by roonyh** [comment]
@shashank-sharma Looks good enough for me. @abdulhannanali sure. go ahead and make your changes.

Make this a seperate wiki page. Don't edit the Home page.

Add a link to this from the README.md. 
In README where it says

" It's developed using the electron platform. [Learn more] " <-- This should link to this article.

**Comment by shashank-sharma** [comment]
@roonyh Ok, I have made separate page for that and link has been added in the PR.

**Comment by roonyh** [comment]
merged. thanks!
